/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedOperacionalRouteImport } from './routes/_authenticated/operacional'
import { Route as AuthenticatedMiddleRouteImport } from './routes/_authenticated/middle'
import { Route as AuthenticatedJuridicoRouteImport } from './routes/_authenticated/juridico'
import { Route as AuthenticatedHubRouteImport } from './routes/_authenticated/hub'
import { Route as AuthenticatedGarantiaRouteImport } from './routes/_authenticated/garantia'
import { Route as AuthenticatedFinanceiroRouteImport } from './routes/_authenticated/financeiro'
import { Route as AuthenticatedFacilitiesRouteImport } from './routes/_authenticated/facilities'
import { Route as AuthenticatedDemaisRamosRouteImport } from './routes/_authenticated/demais-ramos'
import { Route as AuthenticatedComunicadosRouteImport } from './routes/_authenticated/comunicados'
import { Route as AuthenticatedBeneficiosRouteImport } from './routes/_authenticated/beneficios'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/admin/route'
import { Route as AuthenticatedDashboardReceitaExecutivoRouteImport } from './routes/_authenticated/dashboard.receita-executivo'
import { Route as AuthenticatedDashboardReceitaCaixaRouteImport } from './routes/_authenticated/dashboard.receita-caixa'
import { Route as AuthenticatedDashboardReceitaRouteImport } from './routes/_authenticated/dashboard.receita'
import { Route as AuthenticatedAdminUsuariosRouteImport } from './routes/_authenticated/admin/usuarios'
import { Route as AuthenticatedAdminPerfisRouteImport } from './routes/_authenticated/admin/perfis'
import { Route as AuthenticatedAdminImportarBasesRouteImport } from './routes/_authenticated/admin/importar-bases'
import { Route as AuthenticatedAdminConfiguracoesRouteImport } from './routes/_authenticated/admin/configuracoes'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedOperacionalRoute =
  AuthenticatedOperacionalRouteImport.update({
    id: '/operacional',
    path: '/operacional',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMiddleRoute = AuthenticatedMiddleRouteImport.update({
  id: '/middle',
  path: '/middle',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedJuridicoRoute = AuthenticatedJuridicoRouteImport.update({
  id: '/juridico',
  path: '/juridico',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHubRoute = AuthenticatedHubRouteImport.update({
  id: '/hub',
  path: '/hub',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGarantiaRoute = AuthenticatedGarantiaRouteImport.update({
  id: '/garantia',
  path: '/garantia',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFinanceiroRoute = AuthenticatedFinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFacilitiesRoute = AuthenticatedFacilitiesRouteImport.update({
  id: '/facilities',
  path: '/facilities',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDemaisRamosRoute =
  AuthenticatedDemaisRamosRouteImport.update({
    id: '/demais-ramos',
    path: '/demais-ramos',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedComunicadosRoute =
  AuthenticatedComunicadosRouteImport.update({
    id: '/comunicados',
    path: '/comunicados',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBeneficiosRoute = AuthenticatedBeneficiosRouteImport.update({
  id: '/beneficios',
  path: '/beneficios',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardReceitaExecutivoRoute =
  AuthenticatedDashboardReceitaExecutivoRouteImport.update({
    id: '/dashboard/receita-executivo',
    path: '/dashboard/receita-executivo',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardReceitaCaixaRoute =
  AuthenticatedDashboardReceitaCaixaRouteImport.update({
    id: '/dashboard/receita-caixa',
    path: '/dashboard/receita-caixa',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardReceitaRoute =
  AuthenticatedDashboardReceitaRouteImport.update({
    id: '/dashboard/receita',
    path: '/dashboard/receita',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminUsuariosRoute =
  AuthenticatedAdminUsuariosRouteImport.update({
    id: '/usuarios',
    path: '/usuarios',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminPerfisRoute =
  AuthenticatedAdminPerfisRouteImport.update({
    id: '/perfis',
    path: '/perfis',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminImportarBasesRoute =
  AuthenticatedAdminImportarBasesRouteImport.update({
    id: '/importar-bases',
    path: '/importar-bases',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminConfiguracoesRoute =
  AuthenticatedAdminConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/beneficios': typeof AuthenticatedBeneficiosRoute
  '/comunicados': typeof AuthenticatedComunicadosRoute
  '/demais-ramos': typeof AuthenticatedDemaisRamosRoute
  '/facilities': typeof AuthenticatedFacilitiesRoute
  '/financeiro': typeof AuthenticatedFinanceiroRoute
  '/garantia': typeof AuthenticatedGarantiaRoute
  '/hub': typeof AuthenticatedHubRoute
  '/juridico': typeof AuthenticatedJuridicoRoute
  '/middle': typeof AuthenticatedMiddleRoute
  '/operacional': typeof AuthenticatedOperacionalRoute
  '/admin/configuracoes': typeof AuthenticatedAdminConfiguracoesRoute
  '/admin/importar-bases': typeof AuthenticatedAdminImportarBasesRoute
  '/admin/perfis': typeof AuthenticatedAdminPerfisRoute
  '/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/dashboard/receita': typeof AuthenticatedDashboardReceitaRoute
  '/dashboard/receita-caixa': typeof AuthenticatedDashboardReceitaCaixaRoute
  '/dashboard/receita-executivo': typeof AuthenticatedDashboardReceitaExecutivoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/beneficios': typeof AuthenticatedBeneficiosRoute
  '/comunicados': typeof AuthenticatedComunicadosRoute
  '/demais-ramos': typeof AuthenticatedDemaisRamosRoute
  '/facilities': typeof AuthenticatedFacilitiesRoute
  '/financeiro': typeof AuthenticatedFinanceiroRoute
  '/garantia': typeof AuthenticatedGarantiaRoute
  '/hub': typeof AuthenticatedHubRoute
  '/juridico': typeof AuthenticatedJuridicoRoute
  '/middle': typeof AuthenticatedMiddleRoute
  '/operacional': typeof AuthenticatedOperacionalRoute
  '/admin/configuracoes': typeof AuthenticatedAdminConfiguracoesRoute
  '/admin/importar-bases': typeof AuthenticatedAdminImportarBasesRoute
  '/admin/perfis': typeof AuthenticatedAdminPerfisRoute
  '/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/dashboard/receita': typeof AuthenticatedDashboardReceitaRoute
  '/dashboard/receita-caixa': typeof AuthenticatedDashboardReceitaCaixaRoute
  '/dashboard/receita-executivo': typeof AuthenticatedDashboardReceitaExecutivoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/_authenticated/beneficios': typeof AuthenticatedBeneficiosRoute
  '/_authenticated/comunicados': typeof AuthenticatedComunicadosRoute
  '/_authenticated/demais-ramos': typeof AuthenticatedDemaisRamosRoute
  '/_authenticated/facilities': typeof AuthenticatedFacilitiesRoute
  '/_authenticated/financeiro': typeof AuthenticatedFinanceiroRoute
  '/_authenticated/garantia': typeof AuthenticatedGarantiaRoute
  '/_authenticated/hub': typeof AuthenticatedHubRoute
  '/_authenticated/juridico': typeof AuthenticatedJuridicoRoute
  '/_authenticated/middle': typeof AuthenticatedMiddleRoute
  '/_authenticated/operacional': typeof AuthenticatedOperacionalRoute
  '/_authenticated/admin/configuracoes': typeof AuthenticatedAdminConfiguracoesRoute
  '/_authenticated/admin/importar-bases': typeof AuthenticatedAdminImportarBasesRoute
  '/_authenticated/admin/perfis': typeof AuthenticatedAdminPerfisRoute
  '/_authenticated/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/_authenticated/dashboard/receita': typeof AuthenticatedDashboardReceitaRoute
  '/_authenticated/dashboard/receita-caixa': typeof AuthenticatedDashboardReceitaCaixaRoute
  '/_authenticated/dashboard/receita-executivo': typeof AuthenticatedDashboardReceitaExecutivoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/admin'
    | '/beneficios'
    | '/comunicados'
    | '/demais-ramos'
    | '/facilities'
    | '/financeiro'
    | '/garantia'
    | '/hub'
    | '/juridico'
    | '/middle'
    | '/operacional'
    | '/admin/configuracoes'
    | '/admin/importar-bases'
    | '/admin/perfis'
    | '/admin/usuarios'
    | '/dashboard/receita'
    | '/dashboard/receita-caixa'
    | '/dashboard/receita-executivo'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/admin'
    | '/beneficios'
    | '/comunicados'
    | '/demais-ramos'
    | '/facilities'
    | '/financeiro'
    | '/garantia'
    | '/hub'
    | '/juridico'
    | '/middle'
    | '/operacional'
    | '/admin/configuracoes'
    | '/admin/importar-bases'
    | '/admin/perfis'
    | '/admin/usuarios'
    | '/dashboard/receita'
    | '/dashboard/receita-caixa'
    | '/dashboard/receita-executivo'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/admin'
    | '/_authenticated/beneficios'
    | '/_authenticated/comunicados'
    | '/_authenticated/demais-ramos'
    | '/_authenticated/facilities'
    | '/_authenticated/financeiro'
    | '/_authenticated/garantia'
    | '/_authenticated/hub'
    | '/_authenticated/juridico'
    | '/_authenticated/middle'
    | '/_authenticated/operacional'
    | '/_authenticated/admin/configuracoes'
    | '/_authenticated/admin/importar-bases'
    | '/_authenticated/admin/perfis'
    | '/_authenticated/admin/usuarios'
    | '/_authenticated/dashboard/receita'
    | '/_authenticated/dashboard/receita-caixa'
    | '/_authenticated/dashboard/receita-executivo'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/operacional': {
      id: '/_authenticated/operacional'
      path: '/operacional'
      fullPath: '/operacional'
      preLoaderRoute: typeof AuthenticatedOperacionalRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/middle': {
      id: '/_authenticated/middle'
      path: '/middle'
      fullPath: '/middle'
      preLoaderRoute: typeof AuthenticatedMiddleRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/juridico': {
      id: '/_authenticated/juridico'
      path: '/juridico'
      fullPath: '/juridico'
      preLoaderRoute: typeof AuthenticatedJuridicoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/hub': {
      id: '/_authenticated/hub'
      path: '/hub'
      fullPath: '/hub'
      preLoaderRoute: typeof AuthenticatedHubRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/garantia': {
      id: '/_authenticated/garantia'
      path: '/garantia'
      fullPath: '/garantia'
      preLoaderRoute: typeof AuthenticatedGarantiaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/financeiro': {
      id: '/_authenticated/financeiro'
      path: '/financeiro'
      fullPath: '/financeiro'
      preLoaderRoute: typeof AuthenticatedFinanceiroRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/facilities': {
      id: '/_authenticated/facilities'
      path: '/facilities'
      fullPath: '/facilities'
      preLoaderRoute: typeof AuthenticatedFacilitiesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/demais-ramos': {
      id: '/_authenticated/demais-ramos'
      path: '/demais-ramos'
      fullPath: '/demais-ramos'
      preLoaderRoute: typeof AuthenticatedDemaisRamosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/comunicados': {
      id: '/_authenticated/comunicados'
      path: '/comunicados'
      fullPath: '/comunicados'
      preLoaderRoute: typeof AuthenticatedComunicadosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/beneficios': {
      id: '/_authenticated/beneficios'
      path: '/beneficios'
      fullPath: '/beneficios'
      preLoaderRoute: typeof AuthenticatedBeneficiosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/receita-executivo': {
      id: '/_authenticated/dashboard/receita-executivo'
      path: '/dashboard/receita-executivo'
      fullPath: '/dashboard/receita-executivo'
      preLoaderRoute: typeof AuthenticatedDashboardReceitaExecutivoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/receita-caixa': {
      id: '/_authenticated/dashboard/receita-caixa'
      path: '/dashboard/receita-caixa'
      fullPath: '/dashboard/receita-caixa'
      preLoaderRoute: typeof AuthenticatedDashboardReceitaCaixaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/receita': {
      id: '/_authenticated/dashboard/receita'
      path: '/dashboard/receita'
      fullPath: '/dashboard/receita'
      preLoaderRoute: typeof AuthenticatedDashboardReceitaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/usuarios': {
      id: '/_authenticated/admin/usuarios'
      path: '/usuarios'
      fullPath: '/admin/usuarios'
      preLoaderRoute: typeof AuthenticatedAdminUsuariosRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/perfis': {
      id: '/_authenticated/admin/perfis'
      path: '/perfis'
      fullPath: '/admin/perfis'
      preLoaderRoute: typeof AuthenticatedAdminPerfisRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/importar-bases': {
      id: '/_authenticated/admin/importar-bases'
      path: '/importar-bases'
      fullPath: '/admin/importar-bases'
      preLoaderRoute: typeof AuthenticatedAdminImportarBasesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/configuracoes': {
      id: '/_authenticated/admin/configuracoes'
      path: '/configuracoes'
      fullPath: '/admin/configuracoes'
      preLoaderRoute: typeof AuthenticatedAdminConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
  }
}

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminConfiguracoesRoute: typeof AuthenticatedAdminConfiguracoesRoute
  AuthenticatedAdminImportarBasesRoute: typeof AuthenticatedAdminImportarBasesRoute
  AuthenticatedAdminPerfisRoute: typeof AuthenticatedAdminPerfisRoute
  AuthenticatedAdminUsuariosRoute: typeof AuthenticatedAdminUsuariosRoute
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminConfiguracoesRoute: AuthenticatedAdminConfiguracoesRoute,
    AuthenticatedAdminImportarBasesRoute: AuthenticatedAdminImportarBasesRoute,
    AuthenticatedAdminPerfisRoute: AuthenticatedAdminPerfisRoute,
    AuthenticatedAdminUsuariosRoute: AuthenticatedAdminUsuariosRoute,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
  AuthenticatedBeneficiosRoute: typeof AuthenticatedBeneficiosRoute
  AuthenticatedComunicadosRoute: typeof AuthenticatedComunicadosRoute
  AuthenticatedDemaisRamosRoute: typeof AuthenticatedDemaisRamosRoute
  AuthenticatedFacilitiesRoute: typeof AuthenticatedFacilitiesRoute
  AuthenticatedFinanceiroRoute: typeof AuthenticatedFinanceiroRoute
  AuthenticatedGarantiaRoute: typeof AuthenticatedGarantiaRoute
  AuthenticatedHubRoute: typeof AuthenticatedHubRoute
  AuthenticatedJuridicoRoute: typeof AuthenticatedJuridicoRoute
  AuthenticatedMiddleRoute: typeof AuthenticatedMiddleRoute
  AuthenticatedOperacionalRoute: typeof AuthenticatedOperacionalRoute
  AuthenticatedDashboardReceitaRoute: typeof AuthenticatedDashboardReceitaRoute
  AuthenticatedDashboardReceitaCaixaRoute: typeof AuthenticatedDashboardReceitaCaixaRoute
  AuthenticatedDashboardReceitaExecutivoRoute: typeof AuthenticatedDashboardReceitaExecutivoRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
  AuthenticatedBeneficiosRoute: AuthenticatedBeneficiosRoute,
  AuthenticatedComunicadosRoute: AuthenticatedComunicadosRoute,
  AuthenticatedDemaisRamosRoute: AuthenticatedDemaisRamosRoute,
  AuthenticatedFacilitiesRoute: AuthenticatedFacilitiesRoute,
  AuthenticatedFinanceiroRoute: AuthenticatedFinanceiroRoute,
  AuthenticatedGarantiaRoute: AuthenticatedGarantiaRoute,
  AuthenticatedHubRoute: AuthenticatedHubRoute,
  AuthenticatedJuridicoRoute: AuthenticatedJuridicoRoute,
  AuthenticatedMiddleRoute: AuthenticatedMiddleRoute,
  AuthenticatedOperacionalRoute: AuthenticatedOperacionalRoute,
  AuthenticatedDashboardReceitaRoute: AuthenticatedDashboardReceitaRoute,
  AuthenticatedDashboardReceitaCaixaRoute:
    AuthenticatedDashboardReceitaCaixaRoute,
  AuthenticatedDashboardReceitaExecutivoRoute:
    AuthenticatedDashboardReceitaExecutivoRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
