/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthSenhaRouteImport } from './routes/auth.senha'
import { Route as AuthenticatedOperacionalRouteImport } from './routes/_authenticated/operacional'
import { Route as AuthenticatedMiddleRouteImport } from './routes/_authenticated/middle'
import { Route as AuthenticatedJuridicoRouteImport } from './routes/_authenticated/juridico'
import { Route as AuthenticatedInicioRouteImport } from './routes/_authenticated/inicio'
import { Route as AuthenticatedHubRouteImport } from './routes/_authenticated/hub'
import { Route as AuthenticatedGarantiaRouteImport } from './routes/_authenticated/garantia'
import { Route as AuthenticatedFinanceiroRouteImport } from './routes/_authenticated/financeiro'
import { Route as AuthenticatedFacilitiesRouteImport } from './routes/_authenticated/facilities'
import { Route as AuthenticatedDemaisRamosRouteImport } from './routes/_authenticated/demais-ramos'
import { Route as AuthenticatedBeneficiosRouteImport } from './routes/_authenticated/beneficios'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/admin/route'
import { Route as ApiTcLavoroLimitsQueryRouteImport } from './routes/api/tc-lavoro/limits-query'
import { Route as ApiTcLavoroLegacyAnalysisRouteImport } from './routes/api/tc-lavoro/legacy-analysis'
import { Route as ApiTcLavoroAnalysisJobsRouteImport } from './routes/api/tc-lavoro/analysis-jobs'
import { Route as ApiAbSolicitarRouteImport } from './routes/api/ab/solicitar'
import { Route as ApiAbExecutarRouteImport } from './routes/api/ab/executar'
import { Route as ApiAbCotaRouteImport } from './routes/api/ab/cota'
import { Route as ApiAbBgcheckRouteImport } from './routes/api/ab/bgcheck'
import { Route as AuthenticatedJuridicoAnaliseBackgroundRouteImport } from './routes/_authenticated/juridico_.analise-background'
import { Route as AuthenticatedGarantiaAnaliseLimiteRouteImport } from './routes/_authenticated/garantia_.analise-limite'
import { Route as AuthenticatedDashboardReportFechamentoRouteImport } from './routes/_authenticated/dashboard.report-fechamento'
import { Route as AuthenticatedDashboardReceitaExecutivoRouteImport } from './routes/_authenticated/dashboard.receita-executivo'
import { Route as AuthenticatedDashboardReceitaCaixaRouteImport } from './routes/_authenticated/dashboard.receita-caixa'
import { Route as AuthenticatedDashboardReceitaRouteImport } from './routes/_authenticated/dashboard.receita'
import { Route as AuthenticatedAdminUsuariosRouteImport } from './routes/_authenticated/admin/usuarios'
import { Route as AuthenticatedAdminPerfisRouteImport } from './routes/_authenticated/admin/perfis'
import { Route as AuthenticatedAdminImportarBasesRouteImport } from './routes/_authenticated/admin/importar-bases'
import { Route as AuthenticatedAdminEmailsRouteImport } from './routes/_authenticated/admin/emails'
import { Route as AuthenticatedAdminConfiguracoesRouteImport } from './routes/_authenticated/admin/configuracoes'
import { Route as AuthenticatedAdminComunicadosRouteImport } from './routes/_authenticated/admin/comunicados'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'
import { Route as ApiTcLavoroAnalysisJobsJobIdRouteImport } from './routes/api/tc-lavoro/analysis-jobs.$jobId'
import { Route as ApiPublicHooksDispatchScheduledNewslettersRouteImport } from './routes/api/public/hooks/dispatch-scheduled-newsletters'
import { Route as ApiPublicHooksAbMotorRunRouteImport } from './routes/api/public/hooks/ab-motor-run'
import { Route as ApiPublicHooksAbIngestTransparenciaRouteImport } from './routes/api/public/hooks/ab-ingest-transparencia'
import { Route as ApiPublicHooksAbIngestPncpRouteImport } from './routes/api/public/hooks/ab-ingest-pncp'
import { Route as ApiPublicHooksAbIngestPgfnRouteImport } from './routes/api/public/hooks/ab-ingest-pgfn'
import { Route as ApiPublicHooksAbBureauWebhookRouteImport } from './routes/api/public/hooks/ab-bureau-webhook'
import { Route as AuthenticatedAdminEmailsSchedulesRouteImport } from './routes/_authenticated/admin/emails_.schedules'
import { Route as AuthenticatedAdminEmailsLogRouteImport } from './routes/_authenticated/admin/emails_.log'
import { Route as ApiTcLavoroAnalysisJobsJobIdRunRouteImport } from './routes/api/tc-lavoro/analysis-jobs.$jobId.run'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSenhaRoute = AuthSenhaRouteImport.update({
  id: '/senha',
  path: '/senha',
  getParentRoute: () => AuthRoute,
} as any)
const AuthenticatedOperacionalRoute =
  AuthenticatedOperacionalRouteImport.update({
    id: '/operacional',
    path: '/operacional',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMiddleRoute = AuthenticatedMiddleRouteImport.update({
  id: '/middle',
  path: '/middle',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedJuridicoRoute = AuthenticatedJuridicoRouteImport.update({
  id: '/juridico',
  path: '/juridico',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInicioRoute = AuthenticatedInicioRouteImport.update({
  id: '/inicio',
  path: '/inicio',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHubRoute = AuthenticatedHubRouteImport.update({
  id: '/hub',
  path: '/hub',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGarantiaRoute = AuthenticatedGarantiaRouteImport.update({
  id: '/garantia',
  path: '/garantia',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFinanceiroRoute = AuthenticatedFinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFacilitiesRoute = AuthenticatedFacilitiesRouteImport.update({
  id: '/facilities',
  path: '/facilities',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDemaisRamosRoute =
  AuthenticatedDemaisRamosRouteImport.update({
    id: '/demais-ramos',
    path: '/demais-ramos',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBeneficiosRoute = AuthenticatedBeneficiosRouteImport.update({
  id: '/beneficios',
  path: '/beneficios',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiTcLavoroLimitsQueryRoute = ApiTcLavoroLimitsQueryRouteImport.update({
  id: '/api/tc-lavoro/limits-query',
  path: '/api/tc-lavoro/limits-query',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTcLavoroLegacyAnalysisRoute =
  ApiTcLavoroLegacyAnalysisRouteImport.update({
    id: '/api/tc-lavoro/legacy-analysis',
    path: '/api/tc-lavoro/legacy-analysis',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiTcLavoroAnalysisJobsRoute = ApiTcLavoroAnalysisJobsRouteImport.update({
  id: '/api/tc-lavoro/analysis-jobs',
  path: '/api/tc-lavoro/analysis-jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAbSolicitarRoute = ApiAbSolicitarRouteImport.update({
  id: '/api/ab/solicitar',
  path: '/api/ab/solicitar',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAbExecutarRoute = ApiAbExecutarRouteImport.update({
  id: '/api/ab/executar',
  path: '/api/ab/executar',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAbCotaRoute = ApiAbCotaRouteImport.update({
  id: '/api/ab/cota',
  path: '/api/ab/cota',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAbBgcheckRoute = ApiAbBgcheckRouteImport.update({
  id: '/api/ab/bgcheck',
  path: '/api/ab/bgcheck',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedJuridicoAnaliseBackgroundRoute =
  AuthenticatedJuridicoAnaliseBackgroundRouteImport.update({
    id: '/juridico_/analise-background',
    path: '/juridico/analise-background',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedGarantiaAnaliseLimiteRoute =
  AuthenticatedGarantiaAnaliseLimiteRouteImport.update({
    id: '/garantia_/analise-limite',
    path: '/garantia/analise-limite',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardReportFechamentoRoute =
  AuthenticatedDashboardReportFechamentoRouteImport.update({
    id: '/dashboard/report-fechamento',
    path: '/dashboard/report-fechamento',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardReceitaExecutivoRoute =
  AuthenticatedDashboardReceitaExecutivoRouteImport.update({
    id: '/dashboard/receita-executivo',
    path: '/dashboard/receita-executivo',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardReceitaCaixaRoute =
  AuthenticatedDashboardReceitaCaixaRouteImport.update({
    id: '/dashboard/receita-caixa',
    path: '/dashboard/receita-caixa',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardReceitaRoute =
  AuthenticatedDashboardReceitaRouteImport.update({
    id: '/dashboard/receita',
    path: '/dashboard/receita',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminUsuariosRoute =
  AuthenticatedAdminUsuariosRouteImport.update({
    id: '/usuarios',
    path: '/usuarios',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminPerfisRoute =
  AuthenticatedAdminPerfisRouteImport.update({
    id: '/perfis',
    path: '/perfis',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminImportarBasesRoute =
  AuthenticatedAdminImportarBasesRouteImport.update({
    id: '/importar-bases',
    path: '/importar-bases',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminEmailsRoute =
  AuthenticatedAdminEmailsRouteImport.update({
    id: '/emails',
    path: '/emails',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminConfiguracoesRoute =
  AuthenticatedAdminConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminComunicadosRoute =
  AuthenticatedAdminComunicadosRouteImport.update({
    id: '/comunicados',
    path: '/comunicados',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTcLavoroAnalysisJobsJobIdRoute =
  ApiTcLavoroAnalysisJobsJobIdRouteImport.update({
    id: '/$jobId',
    path: '/$jobId',
    getParentRoute: () => ApiTcLavoroAnalysisJobsRoute,
  } as any)
const ApiPublicHooksDispatchScheduledNewslettersRoute =
  ApiPublicHooksDispatchScheduledNewslettersRouteImport.update({
    id: '/api/public/hooks/dispatch-scheduled-newsletters',
    path: '/api/public/hooks/dispatch-scheduled-newsletters',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksAbMotorRunRoute =
  ApiPublicHooksAbMotorRunRouteImport.update({
    id: '/api/public/hooks/ab-motor-run',
    path: '/api/public/hooks/ab-motor-run',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksAbIngestTransparenciaRoute =
  ApiPublicHooksAbIngestTransparenciaRouteImport.update({
    id: '/api/public/hooks/ab-ingest-transparencia',
    path: '/api/public/hooks/ab-ingest-transparencia',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksAbIngestPncpRoute =
  ApiPublicHooksAbIngestPncpRouteImport.update({
    id: '/api/public/hooks/ab-ingest-pncp',
    path: '/api/public/hooks/ab-ingest-pncp',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksAbIngestPgfnRoute =
  ApiPublicHooksAbIngestPgfnRouteImport.update({
    id: '/api/public/hooks/ab-ingest-pgfn',
    path: '/api/public/hooks/ab-ingest-pgfn',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksAbBureauWebhookRoute =
  ApiPublicHooksAbBureauWebhookRouteImport.update({
    id: '/api/public/hooks/ab-bureau-webhook',
    path: '/api/public/hooks/ab-bureau-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAdminEmailsSchedulesRoute =
  AuthenticatedAdminEmailsSchedulesRouteImport.update({
    id: '/emails_/schedules',
    path: '/emails/schedules',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminEmailsLogRoute =
  AuthenticatedAdminEmailsLogRouteImport.update({
    id: '/emails_/log',
    path: '/emails/log',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const ApiTcLavoroAnalysisJobsJobIdRunRoute =
  ApiTcLavoroAnalysisJobsJobIdRunRouteImport.update({
    id: '/run',
    path: '/run',
    getParentRoute: () => ApiTcLavoroAnalysisJobsJobIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/beneficios': typeof AuthenticatedBeneficiosRoute
  '/demais-ramos': typeof AuthenticatedDemaisRamosRoute
  '/facilities': typeof AuthenticatedFacilitiesRoute
  '/financeiro': typeof AuthenticatedFinanceiroRoute
  '/garantia': typeof AuthenticatedGarantiaRoute
  '/hub': typeof AuthenticatedHubRoute
  '/inicio': typeof AuthenticatedInicioRoute
  '/juridico': typeof AuthenticatedJuridicoRoute
  '/middle': typeof AuthenticatedMiddleRoute
  '/operacional': typeof AuthenticatedOperacionalRoute
  '/auth/senha': typeof AuthSenhaRoute
  '/admin/comunicados': typeof AuthenticatedAdminComunicadosRoute
  '/admin/configuracoes': typeof AuthenticatedAdminConfiguracoesRoute
  '/admin/emails': typeof AuthenticatedAdminEmailsRoute
  '/admin/importar-bases': typeof AuthenticatedAdminImportarBasesRoute
  '/admin/perfis': typeof AuthenticatedAdminPerfisRoute
  '/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/dashboard/receita': typeof AuthenticatedDashboardReceitaRoute
  '/dashboard/receita-caixa': typeof AuthenticatedDashboardReceitaCaixaRoute
  '/dashboard/receita-executivo': typeof AuthenticatedDashboardReceitaExecutivoRoute
  '/dashboard/report-fechamento': typeof AuthenticatedDashboardReportFechamentoRoute
  '/garantia/analise-limite': typeof AuthenticatedGarantiaAnaliseLimiteRoute
  '/juridico/analise-background': typeof AuthenticatedJuridicoAnaliseBackgroundRoute
  '/api/ab/bgcheck': typeof ApiAbBgcheckRoute
  '/api/ab/cota': typeof ApiAbCotaRoute
  '/api/ab/executar': typeof ApiAbExecutarRoute
  '/api/ab/solicitar': typeof ApiAbSolicitarRoute
  '/api/tc-lavoro/analysis-jobs': typeof ApiTcLavoroAnalysisJobsRouteWithChildren
  '/api/tc-lavoro/legacy-analysis': typeof ApiTcLavoroLegacyAnalysisRoute
  '/api/tc-lavoro/limits-query': typeof ApiTcLavoroLimitsQueryRoute
  '/admin/emails/log': typeof AuthenticatedAdminEmailsLogRoute
  '/admin/emails/schedules': typeof AuthenticatedAdminEmailsSchedulesRoute
  '/api/public/hooks/ab-bureau-webhook': typeof ApiPublicHooksAbBureauWebhookRoute
  '/api/public/hooks/ab-ingest-pgfn': typeof ApiPublicHooksAbIngestPgfnRoute
  '/api/public/hooks/ab-ingest-pncp': typeof ApiPublicHooksAbIngestPncpRoute
  '/api/public/hooks/ab-ingest-transparencia': typeof ApiPublicHooksAbIngestTransparenciaRoute
  '/api/public/hooks/ab-motor-run': typeof ApiPublicHooksAbMotorRunRoute
  '/api/public/hooks/dispatch-scheduled-newsletters': typeof ApiPublicHooksDispatchScheduledNewslettersRoute
  '/api/tc-lavoro/analysis-jobs/$jobId': typeof ApiTcLavoroAnalysisJobsJobIdRouteWithChildren
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/api/tc-lavoro/analysis-jobs/$jobId/run': typeof ApiTcLavoroAnalysisJobsJobIdRunRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/beneficios': typeof AuthenticatedBeneficiosRoute
  '/demais-ramos': typeof AuthenticatedDemaisRamosRoute
  '/facilities': typeof AuthenticatedFacilitiesRoute
  '/financeiro': typeof AuthenticatedFinanceiroRoute
  '/garantia': typeof AuthenticatedGarantiaRoute
  '/hub': typeof AuthenticatedHubRoute
  '/inicio': typeof AuthenticatedInicioRoute
  '/juridico': typeof AuthenticatedJuridicoRoute
  '/middle': typeof AuthenticatedMiddleRoute
  '/operacional': typeof AuthenticatedOperacionalRoute
  '/auth/senha': typeof AuthSenhaRoute
  '/admin/comunicados': typeof AuthenticatedAdminComunicadosRoute
  '/admin/configuracoes': typeof AuthenticatedAdminConfiguracoesRoute
  '/admin/emails': typeof AuthenticatedAdminEmailsRoute
  '/admin/importar-bases': typeof AuthenticatedAdminImportarBasesRoute
  '/admin/perfis': typeof AuthenticatedAdminPerfisRoute
  '/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/dashboard/receita': typeof AuthenticatedDashboardReceitaRoute
  '/dashboard/receita-caixa': typeof AuthenticatedDashboardReceitaCaixaRoute
  '/dashboard/receita-executivo': typeof AuthenticatedDashboardReceitaExecutivoRoute
  '/dashboard/report-fechamento': typeof AuthenticatedDashboardReportFechamentoRoute
  '/garantia/analise-limite': typeof AuthenticatedGarantiaAnaliseLimiteRoute
  '/juridico/analise-background': typeof AuthenticatedJuridicoAnaliseBackgroundRoute
  '/api/ab/bgcheck': typeof ApiAbBgcheckRoute
  '/api/ab/cota': typeof ApiAbCotaRoute
  '/api/ab/executar': typeof ApiAbExecutarRoute
  '/api/ab/solicitar': typeof ApiAbSolicitarRoute
  '/api/tc-lavoro/analysis-jobs': typeof ApiTcLavoroAnalysisJobsRouteWithChildren
  '/api/tc-lavoro/legacy-analysis': typeof ApiTcLavoroLegacyAnalysisRoute
  '/api/tc-lavoro/limits-query': typeof ApiTcLavoroLimitsQueryRoute
  '/admin/emails/log': typeof AuthenticatedAdminEmailsLogRoute
  '/admin/emails/schedules': typeof AuthenticatedAdminEmailsSchedulesRoute
  '/api/public/hooks/ab-bureau-webhook': typeof ApiPublicHooksAbBureauWebhookRoute
  '/api/public/hooks/ab-ingest-pgfn': typeof ApiPublicHooksAbIngestPgfnRoute
  '/api/public/hooks/ab-ingest-pncp': typeof ApiPublicHooksAbIngestPncpRoute
  '/api/public/hooks/ab-ingest-transparencia': typeof ApiPublicHooksAbIngestTransparenciaRoute
  '/api/public/hooks/ab-motor-run': typeof ApiPublicHooksAbMotorRunRoute
  '/api/public/hooks/dispatch-scheduled-newsletters': typeof ApiPublicHooksDispatchScheduledNewslettersRoute
  '/api/tc-lavoro/analysis-jobs/$jobId': typeof ApiTcLavoroAnalysisJobsJobIdRouteWithChildren
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/api/tc-lavoro/analysis-jobs/$jobId/run': typeof ApiTcLavoroAnalysisJobsJobIdRunRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/_authenticated/beneficios': typeof AuthenticatedBeneficiosRoute
  '/_authenticated/demais-ramos': typeof AuthenticatedDemaisRamosRoute
  '/_authenticated/facilities': typeof AuthenticatedFacilitiesRoute
  '/_authenticated/financeiro': typeof AuthenticatedFinanceiroRoute
  '/_authenticated/garantia': typeof AuthenticatedGarantiaRoute
  '/_authenticated/hub': typeof AuthenticatedHubRoute
  '/_authenticated/inicio': typeof AuthenticatedInicioRoute
  '/_authenticated/juridico': typeof AuthenticatedJuridicoRoute
  '/_authenticated/middle': typeof AuthenticatedMiddleRoute
  '/_authenticated/operacional': typeof AuthenticatedOperacionalRoute
  '/auth/senha': typeof AuthSenhaRoute
  '/_authenticated/admin/comunicados': typeof AuthenticatedAdminComunicadosRoute
  '/_authenticated/admin/configuracoes': typeof AuthenticatedAdminConfiguracoesRoute
  '/_authenticated/admin/emails': typeof AuthenticatedAdminEmailsRoute
  '/_authenticated/admin/importar-bases': typeof AuthenticatedAdminImportarBasesRoute
  '/_authenticated/admin/perfis': typeof AuthenticatedAdminPerfisRoute
  '/_authenticated/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/_authenticated/dashboard/receita': typeof AuthenticatedDashboardReceitaRoute
  '/_authenticated/dashboard/receita-caixa': typeof AuthenticatedDashboardReceitaCaixaRoute
  '/_authenticated/dashboard/receita-executivo': typeof AuthenticatedDashboardReceitaExecutivoRoute
  '/_authenticated/dashboard/report-fechamento': typeof AuthenticatedDashboardReportFechamentoRoute
  '/_authenticated/garantia_/analise-limite': typeof AuthenticatedGarantiaAnaliseLimiteRoute
  '/_authenticated/juridico_/analise-background': typeof AuthenticatedJuridicoAnaliseBackgroundRoute
  '/api/ab/bgcheck': typeof ApiAbBgcheckRoute
  '/api/ab/cota': typeof ApiAbCotaRoute
  '/api/ab/executar': typeof ApiAbExecutarRoute
  '/api/ab/solicitar': typeof ApiAbSolicitarRoute
  '/api/tc-lavoro/analysis-jobs': typeof ApiTcLavoroAnalysisJobsRouteWithChildren
  '/api/tc-lavoro/legacy-analysis': typeof ApiTcLavoroLegacyAnalysisRoute
  '/api/tc-lavoro/limits-query': typeof ApiTcLavoroLimitsQueryRoute
  '/_authenticated/admin/emails_/log': typeof AuthenticatedAdminEmailsLogRoute
  '/_authenticated/admin/emails_/schedules': typeof AuthenticatedAdminEmailsSchedulesRoute
  '/api/public/hooks/ab-bureau-webhook': typeof ApiPublicHooksAbBureauWebhookRoute
  '/api/public/hooks/ab-ingest-pgfn': typeof ApiPublicHooksAbIngestPgfnRoute
  '/api/public/hooks/ab-ingest-pncp': typeof ApiPublicHooksAbIngestPncpRoute
  '/api/public/hooks/ab-ingest-transparencia': typeof ApiPublicHooksAbIngestTransparenciaRoute
  '/api/public/hooks/ab-motor-run': typeof ApiPublicHooksAbMotorRunRoute
  '/api/public/hooks/dispatch-scheduled-newsletters': typeof ApiPublicHooksDispatchScheduledNewslettersRoute
  '/api/tc-lavoro/analysis-jobs/$jobId': typeof ApiTcLavoroAnalysisJobsJobIdRouteWithChildren
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/api/tc-lavoro/analysis-jobs/$jobId/run': typeof ApiTcLavoroAnalysisJobsJobIdRunRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/admin'
    | '/beneficios'
    | '/demais-ramos'
    | '/facilities'
    | '/financeiro'
    | '/garantia'
    | '/hub'
    | '/inicio'
    | '/juridico'
    | '/middle'
    | '/operacional'
    | '/auth/senha'
    | '/admin/comunicados'
    | '/admin/configuracoes'
    | '/admin/emails'
    | '/admin/importar-bases'
    | '/admin/perfis'
    | '/admin/usuarios'
    | '/dashboard/receita'
    | '/dashboard/receita-caixa'
    | '/dashboard/receita-executivo'
    | '/dashboard/report-fechamento'
    | '/garantia/analise-limite'
    | '/juridico/analise-background'
    | '/api/ab/bgcheck'
    | '/api/ab/cota'
    | '/api/ab/executar'
    | '/api/ab/solicitar'
    | '/api/tc-lavoro/analysis-jobs'
    | '/api/tc-lavoro/legacy-analysis'
    | '/api/tc-lavoro/limits-query'
    | '/admin/emails/log'
    | '/admin/emails/schedules'
    | '/api/public/hooks/ab-bureau-webhook'
    | '/api/public/hooks/ab-ingest-pgfn'
    | '/api/public/hooks/ab-ingest-pncp'
    | '/api/public/hooks/ab-ingest-transparencia'
    | '/api/public/hooks/ab-motor-run'
    | '/api/public/hooks/dispatch-scheduled-newsletters'
    | '/api/tc-lavoro/analysis-jobs/$jobId'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/transactional/preview'
    | '/api/tc-lavoro/analysis-jobs/$jobId/run'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/admin'
    | '/beneficios'
    | '/demais-ramos'
    | '/facilities'
    | '/financeiro'
    | '/garantia'
    | '/hub'
    | '/inicio'
    | '/juridico'
    | '/middle'
    | '/operacional'
    | '/auth/senha'
    | '/admin/comunicados'
    | '/admin/configuracoes'
    | '/admin/emails'
    | '/admin/importar-bases'
    | '/admin/perfis'
    | '/admin/usuarios'
    | '/dashboard/receita'
    | '/dashboard/receita-caixa'
    | '/dashboard/receita-executivo'
    | '/dashboard/report-fechamento'
    | '/garantia/analise-limite'
    | '/juridico/analise-background'
    | '/api/ab/bgcheck'
    | '/api/ab/cota'
    | '/api/ab/executar'
    | '/api/ab/solicitar'
    | '/api/tc-lavoro/analysis-jobs'
    | '/api/tc-lavoro/legacy-analysis'
    | '/api/tc-lavoro/limits-query'
    | '/admin/emails/log'
    | '/admin/emails/schedules'
    | '/api/public/hooks/ab-bureau-webhook'
    | '/api/public/hooks/ab-ingest-pgfn'
    | '/api/public/hooks/ab-ingest-pncp'
    | '/api/public/hooks/ab-ingest-transparencia'
    | '/api/public/hooks/ab-motor-run'
    | '/api/public/hooks/dispatch-scheduled-newsletters'
    | '/api/tc-lavoro/analysis-jobs/$jobId'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/transactional/preview'
    | '/api/tc-lavoro/analysis-jobs/$jobId/run'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/_authenticated/admin'
    | '/_authenticated/beneficios'
    | '/_authenticated/demais-ramos'
    | '/_authenticated/facilities'
    | '/_authenticated/financeiro'
    | '/_authenticated/garantia'
    | '/_authenticated/hub'
    | '/_authenticated/inicio'
    | '/_authenticated/juridico'
    | '/_authenticated/middle'
    | '/_authenticated/operacional'
    | '/auth/senha'
    | '/_authenticated/admin/comunicados'
    | '/_authenticated/admin/configuracoes'
    | '/_authenticated/admin/emails'
    | '/_authenticated/admin/importar-bases'
    | '/_authenticated/admin/perfis'
    | '/_authenticated/admin/usuarios'
    | '/_authenticated/dashboard/receita'
    | '/_authenticated/dashboard/receita-caixa'
    | '/_authenticated/dashboard/receita-executivo'
    | '/_authenticated/dashboard/report-fechamento'
    | '/_authenticated/garantia_/analise-limite'
    | '/_authenticated/juridico_/analise-background'
    | '/api/ab/bgcheck'
    | '/api/ab/cota'
    | '/api/ab/executar'
    | '/api/ab/solicitar'
    | '/api/tc-lavoro/analysis-jobs'
    | '/api/tc-lavoro/legacy-analysis'
    | '/api/tc-lavoro/limits-query'
    | '/_authenticated/admin/emails_/log'
    | '/_authenticated/admin/emails_/schedules'
    | '/api/public/hooks/ab-bureau-webhook'
    | '/api/public/hooks/ab-ingest-pgfn'
    | '/api/public/hooks/ab-ingest-pncp'
    | '/api/public/hooks/ab-ingest-transparencia'
    | '/api/public/hooks/ab-motor-run'
    | '/api/public/hooks/dispatch-scheduled-newsletters'
    | '/api/tc-lavoro/analysis-jobs/$jobId'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/transactional/preview'
    | '/api/tc-lavoro/analysis-jobs/$jobId/run'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  ResetPasswordRoute: typeof ResetPasswordRoute
  ApiAbBgcheckRoute: typeof ApiAbBgcheckRoute
  ApiAbCotaRoute: typeof ApiAbCotaRoute
  ApiAbExecutarRoute: typeof ApiAbExecutarRoute
  ApiAbSolicitarRoute: typeof ApiAbSolicitarRoute
  ApiTcLavoroAnalysisJobsRoute: typeof ApiTcLavoroAnalysisJobsRouteWithChildren
  ApiTcLavoroLegacyAnalysisRoute: typeof ApiTcLavoroLegacyAnalysisRoute
  ApiTcLavoroLimitsQueryRoute: typeof ApiTcLavoroLimitsQueryRoute
  ApiPublicHooksAbBureauWebhookRoute: typeof ApiPublicHooksAbBureauWebhookRoute
  ApiPublicHooksAbIngestPgfnRoute: typeof ApiPublicHooksAbIngestPgfnRoute
  ApiPublicHooksAbIngestPncpRoute: typeof ApiPublicHooksAbIngestPncpRoute
  ApiPublicHooksAbIngestTransparenciaRoute: typeof ApiPublicHooksAbIngestTransparenciaRoute
  ApiPublicHooksAbMotorRunRoute: typeof ApiPublicHooksAbMotorRunRoute
  ApiPublicHooksDispatchScheduledNewslettersRoute: typeof ApiPublicHooksDispatchScheduledNewslettersRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/senha': {
      id: '/auth/senha'
      path: '/senha'
      fullPath: '/auth/senha'
      preLoaderRoute: typeof AuthSenhaRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_authenticated/operacional': {
      id: '/_authenticated/operacional'
      path: '/operacional'
      fullPath: '/operacional'
      preLoaderRoute: typeof AuthenticatedOperacionalRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/middle': {
      id: '/_authenticated/middle'
      path: '/middle'
      fullPath: '/middle'
      preLoaderRoute: typeof AuthenticatedMiddleRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/juridico': {
      id: '/_authenticated/juridico'
      path: '/juridico'
      fullPath: '/juridico'
      preLoaderRoute: typeof AuthenticatedJuridicoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inicio': {
      id: '/_authenticated/inicio'
      path: '/inicio'
      fullPath: '/inicio'
      preLoaderRoute: typeof AuthenticatedInicioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/hub': {
      id: '/_authenticated/hub'
      path: '/hub'
      fullPath: '/hub'
      preLoaderRoute: typeof AuthenticatedHubRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/garantia': {
      id: '/_authenticated/garantia'
      path: '/garantia'
      fullPath: '/garantia'
      preLoaderRoute: typeof AuthenticatedGarantiaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/financeiro': {
      id: '/_authenticated/financeiro'
      path: '/financeiro'
      fullPath: '/financeiro'
      preLoaderRoute: typeof AuthenticatedFinanceiroRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/facilities': {
      id: '/_authenticated/facilities'
      path: '/facilities'
      fullPath: '/facilities'
      preLoaderRoute: typeof AuthenticatedFacilitiesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/demais-ramos': {
      id: '/_authenticated/demais-ramos'
      path: '/demais-ramos'
      fullPath: '/demais-ramos'
      preLoaderRoute: typeof AuthenticatedDemaisRamosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/beneficios': {
      id: '/_authenticated/beneficios'
      path: '/beneficios'
      fullPath: '/beneficios'
      preLoaderRoute: typeof AuthenticatedBeneficiosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/tc-lavoro/limits-query': {
      id: '/api/tc-lavoro/limits-query'
      path: '/api/tc-lavoro/limits-query'
      fullPath: '/api/tc-lavoro/limits-query'
      preLoaderRoute: typeof ApiTcLavoroLimitsQueryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tc-lavoro/legacy-analysis': {
      id: '/api/tc-lavoro/legacy-analysis'
      path: '/api/tc-lavoro/legacy-analysis'
      fullPath: '/api/tc-lavoro/legacy-analysis'
      preLoaderRoute: typeof ApiTcLavoroLegacyAnalysisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tc-lavoro/analysis-jobs': {
      id: '/api/tc-lavoro/analysis-jobs'
      path: '/api/tc-lavoro/analysis-jobs'
      fullPath: '/api/tc-lavoro/analysis-jobs'
      preLoaderRoute: typeof ApiTcLavoroAnalysisJobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ab/solicitar': {
      id: '/api/ab/solicitar'
      path: '/api/ab/solicitar'
      fullPath: '/api/ab/solicitar'
      preLoaderRoute: typeof ApiAbSolicitarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ab/executar': {
      id: '/api/ab/executar'
      path: '/api/ab/executar'
      fullPath: '/api/ab/executar'
      preLoaderRoute: typeof ApiAbExecutarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ab/cota': {
      id: '/api/ab/cota'
      path: '/api/ab/cota'
      fullPath: '/api/ab/cota'
      preLoaderRoute: typeof ApiAbCotaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ab/bgcheck': {
      id: '/api/ab/bgcheck'
      path: '/api/ab/bgcheck'
      fullPath: '/api/ab/bgcheck'
      preLoaderRoute: typeof ApiAbBgcheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/juridico_/analise-background': {
      id: '/_authenticated/juridico_/analise-background'
      path: '/juridico/analise-background'
      fullPath: '/juridico/analise-background'
      preLoaderRoute: typeof AuthenticatedJuridicoAnaliseBackgroundRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/garantia_/analise-limite': {
      id: '/_authenticated/garantia_/analise-limite'
      path: '/garantia/analise-limite'
      fullPath: '/garantia/analise-limite'
      preLoaderRoute: typeof AuthenticatedGarantiaAnaliseLimiteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/report-fechamento': {
      id: '/_authenticated/dashboard/report-fechamento'
      path: '/dashboard/report-fechamento'
      fullPath: '/dashboard/report-fechamento'
      preLoaderRoute: typeof AuthenticatedDashboardReportFechamentoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/receita-executivo': {
      id: '/_authenticated/dashboard/receita-executivo'
      path: '/dashboard/receita-executivo'
      fullPath: '/dashboard/receita-executivo'
      preLoaderRoute: typeof AuthenticatedDashboardReceitaExecutivoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/receita-caixa': {
      id: '/_authenticated/dashboard/receita-caixa'
      path: '/dashboard/receita-caixa'
      fullPath: '/dashboard/receita-caixa'
      preLoaderRoute: typeof AuthenticatedDashboardReceitaCaixaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/receita': {
      id: '/_authenticated/dashboard/receita'
      path: '/dashboard/receita'
      fullPath: '/dashboard/receita'
      preLoaderRoute: typeof AuthenticatedDashboardReceitaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/usuarios': {
      id: '/_authenticated/admin/usuarios'
      path: '/usuarios'
      fullPath: '/admin/usuarios'
      preLoaderRoute: typeof AuthenticatedAdminUsuariosRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/perfis': {
      id: '/_authenticated/admin/perfis'
      path: '/perfis'
      fullPath: '/admin/perfis'
      preLoaderRoute: typeof AuthenticatedAdminPerfisRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/importar-bases': {
      id: '/_authenticated/admin/importar-bases'
      path: '/importar-bases'
      fullPath: '/admin/importar-bases'
      preLoaderRoute: typeof AuthenticatedAdminImportarBasesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/emails': {
      id: '/_authenticated/admin/emails'
      path: '/emails'
      fullPath: '/admin/emails'
      preLoaderRoute: typeof AuthenticatedAdminEmailsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/configuracoes': {
      id: '/_authenticated/admin/configuracoes'
      path: '/configuracoes'
      fullPath: '/admin/configuracoes'
      preLoaderRoute: typeof AuthenticatedAdminConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/comunicados': {
      id: '/_authenticated/admin/comunicados'
      path: '/comunicados'
      fullPath: '/admin/comunicados'
      preLoaderRoute: typeof AuthenticatedAdminComunicadosRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tc-lavoro/analysis-jobs/$jobId': {
      id: '/api/tc-lavoro/analysis-jobs/$jobId'
      path: '/$jobId'
      fullPath: '/api/tc-lavoro/analysis-jobs/$jobId'
      preLoaderRoute: typeof ApiTcLavoroAnalysisJobsJobIdRouteImport
      parentRoute: typeof ApiTcLavoroAnalysisJobsRoute
    }
    '/api/public/hooks/dispatch-scheduled-newsletters': {
      id: '/api/public/hooks/dispatch-scheduled-newsletters'
      path: '/api/public/hooks/dispatch-scheduled-newsletters'
      fullPath: '/api/public/hooks/dispatch-scheduled-newsletters'
      preLoaderRoute: typeof ApiPublicHooksDispatchScheduledNewslettersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/ab-motor-run': {
      id: '/api/public/hooks/ab-motor-run'
      path: '/api/public/hooks/ab-motor-run'
      fullPath: '/api/public/hooks/ab-motor-run'
      preLoaderRoute: typeof ApiPublicHooksAbMotorRunRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/ab-ingest-transparencia': {
      id: '/api/public/hooks/ab-ingest-transparencia'
      path: '/api/public/hooks/ab-ingest-transparencia'
      fullPath: '/api/public/hooks/ab-ingest-transparencia'
      preLoaderRoute: typeof ApiPublicHooksAbIngestTransparenciaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/ab-ingest-pncp': {
      id: '/api/public/hooks/ab-ingest-pncp'
      path: '/api/public/hooks/ab-ingest-pncp'
      fullPath: '/api/public/hooks/ab-ingest-pncp'
      preLoaderRoute: typeof ApiPublicHooksAbIngestPncpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/ab-ingest-pgfn': {
      id: '/api/public/hooks/ab-ingest-pgfn'
      path: '/api/public/hooks/ab-ingest-pgfn'
      fullPath: '/api/public/hooks/ab-ingest-pgfn'
      preLoaderRoute: typeof ApiPublicHooksAbIngestPgfnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/ab-bureau-webhook': {
      id: '/api/public/hooks/ab-bureau-webhook'
      path: '/api/public/hooks/ab-bureau-webhook'
      fullPath: '/api/public/hooks/ab-bureau-webhook'
      preLoaderRoute: typeof ApiPublicHooksAbBureauWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/emails_/schedules': {
      id: '/_authenticated/admin/emails_/schedules'
      path: '/emails/schedules'
      fullPath: '/admin/emails/schedules'
      preLoaderRoute: typeof AuthenticatedAdminEmailsSchedulesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/emails_/log': {
      id: '/_authenticated/admin/emails_/log'
      path: '/emails/log'
      fullPath: '/admin/emails/log'
      preLoaderRoute: typeof AuthenticatedAdminEmailsLogRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/api/tc-lavoro/analysis-jobs/$jobId/run': {
      id: '/api/tc-lavoro/analysis-jobs/$jobId/run'
      path: '/run'
      fullPath: '/api/tc-lavoro/analysis-jobs/$jobId/run'
      preLoaderRoute: typeof ApiTcLavoroAnalysisJobsJobIdRunRouteImport
      parentRoute: typeof ApiTcLavoroAnalysisJobsJobIdRoute
    }
  }
}

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminComunicadosRoute: typeof AuthenticatedAdminComunicadosRoute
  AuthenticatedAdminConfiguracoesRoute: typeof AuthenticatedAdminConfiguracoesRoute
  AuthenticatedAdminEmailsRoute: typeof AuthenticatedAdminEmailsRoute
  AuthenticatedAdminImportarBasesRoute: typeof AuthenticatedAdminImportarBasesRoute
  AuthenticatedAdminPerfisRoute: typeof AuthenticatedAdminPerfisRoute
  AuthenticatedAdminUsuariosRoute: typeof AuthenticatedAdminUsuariosRoute
  AuthenticatedAdminEmailsLogRoute: typeof AuthenticatedAdminEmailsLogRoute
  AuthenticatedAdminEmailsSchedulesRoute: typeof AuthenticatedAdminEmailsSchedulesRoute
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminComunicadosRoute: AuthenticatedAdminComunicadosRoute,
    AuthenticatedAdminConfiguracoesRoute: AuthenticatedAdminConfiguracoesRoute,
    AuthenticatedAdminEmailsRoute: AuthenticatedAdminEmailsRoute,
    AuthenticatedAdminImportarBasesRoute: AuthenticatedAdminImportarBasesRoute,
    AuthenticatedAdminPerfisRoute: AuthenticatedAdminPerfisRoute,
    AuthenticatedAdminUsuariosRoute: AuthenticatedAdminUsuariosRoute,
    AuthenticatedAdminEmailsLogRoute: AuthenticatedAdminEmailsLogRoute,
    AuthenticatedAdminEmailsSchedulesRoute:
      AuthenticatedAdminEmailsSchedulesRoute,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
  AuthenticatedBeneficiosRoute: typeof AuthenticatedBeneficiosRoute
  AuthenticatedDemaisRamosRoute: typeof AuthenticatedDemaisRamosRoute
  AuthenticatedFacilitiesRoute: typeof AuthenticatedFacilitiesRoute
  AuthenticatedFinanceiroRoute: typeof AuthenticatedFinanceiroRoute
  AuthenticatedGarantiaRoute: typeof AuthenticatedGarantiaRoute
  AuthenticatedHubRoute: typeof AuthenticatedHubRoute
  AuthenticatedInicioRoute: typeof AuthenticatedInicioRoute
  AuthenticatedJuridicoRoute: typeof AuthenticatedJuridicoRoute
  AuthenticatedMiddleRoute: typeof AuthenticatedMiddleRoute
  AuthenticatedOperacionalRoute: typeof AuthenticatedOperacionalRoute
  AuthenticatedDashboardReceitaRoute: typeof AuthenticatedDashboardReceitaRoute
  AuthenticatedDashboardReceitaCaixaRoute: typeof AuthenticatedDashboardReceitaCaixaRoute
  AuthenticatedDashboardReceitaExecutivoRoute: typeof AuthenticatedDashboardReceitaExecutivoRoute
  AuthenticatedDashboardReportFechamentoRoute: typeof AuthenticatedDashboardReportFechamentoRoute
  AuthenticatedGarantiaAnaliseLimiteRoute: typeof AuthenticatedGarantiaAnaliseLimiteRoute
  AuthenticatedJuridicoAnaliseBackgroundRoute: typeof AuthenticatedJuridicoAnaliseBackgroundRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
  AuthenticatedBeneficiosRoute: AuthenticatedBeneficiosRoute,
  AuthenticatedDemaisRamosRoute: AuthenticatedDemaisRamosRoute,
  AuthenticatedFacilitiesRoute: AuthenticatedFacilitiesRoute,
  AuthenticatedFinanceiroRoute: AuthenticatedFinanceiroRoute,
  AuthenticatedGarantiaRoute: AuthenticatedGarantiaRoute,
  AuthenticatedHubRoute: AuthenticatedHubRoute,
  AuthenticatedInicioRoute: AuthenticatedInicioRoute,
  AuthenticatedJuridicoRoute: AuthenticatedJuridicoRoute,
  AuthenticatedMiddleRoute: AuthenticatedMiddleRoute,
  AuthenticatedOperacionalRoute: AuthenticatedOperacionalRoute,
  AuthenticatedDashboardReceitaRoute: AuthenticatedDashboardReceitaRoute,
  AuthenticatedDashboardReceitaCaixaRoute:
    AuthenticatedDashboardReceitaCaixaRoute,
  AuthenticatedDashboardReceitaExecutivoRoute:
    AuthenticatedDashboardReceitaExecutivoRoute,
  AuthenticatedDashboardReportFechamentoRoute:
    AuthenticatedDashboardReportFechamentoRoute,
  AuthenticatedGarantiaAnaliseLimiteRoute:
    AuthenticatedGarantiaAnaliseLimiteRoute,
  AuthenticatedJuridicoAnaliseBackgroundRoute:
    AuthenticatedJuridicoAnaliseBackgroundRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AuthRouteChildren {
  AuthSenhaRoute: typeof AuthSenhaRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthSenhaRoute: AuthSenhaRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface ApiTcLavoroAnalysisJobsJobIdRouteChildren {
  ApiTcLavoroAnalysisJobsJobIdRunRoute: typeof ApiTcLavoroAnalysisJobsJobIdRunRoute
}

const ApiTcLavoroAnalysisJobsJobIdRouteChildren: ApiTcLavoroAnalysisJobsJobIdRouteChildren =
  {
    ApiTcLavoroAnalysisJobsJobIdRunRoute: ApiTcLavoroAnalysisJobsJobIdRunRoute,
  }

const ApiTcLavoroAnalysisJobsJobIdRouteWithChildren =
  ApiTcLavoroAnalysisJobsJobIdRoute._addFileChildren(
    ApiTcLavoroAnalysisJobsJobIdRouteChildren,
  )

interface ApiTcLavoroAnalysisJobsRouteChildren {
  ApiTcLavoroAnalysisJobsJobIdRoute: typeof ApiTcLavoroAnalysisJobsJobIdRouteWithChildren
}

const ApiTcLavoroAnalysisJobsRouteChildren: ApiTcLavoroAnalysisJobsRouteChildren =
  {
    ApiTcLavoroAnalysisJobsJobIdRoute:
      ApiTcLavoroAnalysisJobsJobIdRouteWithChildren,
  }

const ApiTcLavoroAnalysisJobsRouteWithChildren =
  ApiTcLavoroAnalysisJobsRoute._addFileChildren(
    ApiTcLavoroAnalysisJobsRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  ResetPasswordRoute: ResetPasswordRoute,
  ApiAbBgcheckRoute: ApiAbBgcheckRoute,
  ApiAbCotaRoute: ApiAbCotaRoute,
  ApiAbExecutarRoute: ApiAbExecutarRoute,
  ApiAbSolicitarRoute: ApiAbSolicitarRoute,
  ApiTcLavoroAnalysisJobsRoute: ApiTcLavoroAnalysisJobsRouteWithChildren,
  ApiTcLavoroLegacyAnalysisRoute: ApiTcLavoroLegacyAnalysisRoute,
  ApiTcLavoroLimitsQueryRoute: ApiTcLavoroLimitsQueryRoute,
  ApiPublicHooksAbBureauWebhookRoute: ApiPublicHooksAbBureauWebhookRoute,
  ApiPublicHooksAbIngestPgfnRoute: ApiPublicHooksAbIngestPgfnRoute,
  ApiPublicHooksAbIngestPncpRoute: ApiPublicHooksAbIngestPncpRoute,
  ApiPublicHooksAbIngestTransparenciaRoute:
    ApiPublicHooksAbIngestTransparenciaRoute,
  ApiPublicHooksAbMotorRunRoute: ApiPublicHooksAbMotorRunRoute,
  ApiPublicHooksDispatchScheduledNewslettersRoute:
    ApiPublicHooksDispatchScheduledNewslettersRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
