CREATE OR REPLACE FUNCTION public.lavoro_normaliza_seguradora(p_seguradora text)
RETURNS text
LANGUAGE sql
IMMUTABLE
SET search_path = public
AS $$
  SELECT CASE
    WHEN p_seguradora IS NULL OR btrim(p_seguradora) = '' THEN NULL
    ELSE CASE regexp_replace(lower(btrim(p_seguradora)), '[^a-z0-9]', '', 'g')
      WHEN 'sulamrica' THEN 'Sul América'
      WHEN 'tokio' THEN 'Tokio Marine'
      WHEN 'tokiomarine' THEN 'Tokio Marine'
      WHEN 'porto' THEN 'Porto Seguro'
      WHEN 'portoseguro' THEN 'Porto Seguro'
      WHEN 'newe' THEN 'Newe Seguros'
      WHEN 'neweseguros' THEN 'Newe Seguros'
      WHEN 'aig' THEN 'AIG'
      WHEN 'akad' THEN 'Akad'
      WHEN 'alice' THEN 'Alice'
      WHEN 'allianzeulerhermes' THEN 'Allianz (Euler Hermes)'
      WHEN 'allseguro' THEN 'All Seguro'
      WHEN 'alpha' THEN 'Alpha'
      WHEN 'amil' THEN 'Amil'
      WHEN 'assim' THEN 'Assim'
      WHEN 'austral' THEN 'Austral'
      WHEN 'avla' THEN 'AVLA'
      WHEN 'axa' THEN 'AXA'
      WHEN 'azul' THEN 'Azul'
      WHEN 'berkley' THEN 'Berkley'
      WHEN 'bmg' THEN 'BMG'
      WHEN 'bradesco' THEN 'Bradesco'
      WHEN 'btg' THEN 'BTG'
      WHEN 'caixa' THEN 'Caixa'
      WHEN 'chubb' THEN 'Chubb'
      WHEN 'daycoval' THEN 'Daycoval'
      WHEN 'essor' THEN 'Essor'
      WHEN 'estilocorretora' THEN 'Estilo Corretora'
      WHEN 'excelsior' THEN 'Excelsior'
      WHEN 'ezze' THEN 'Ezze'
      WHEN 'fairfax' THEN 'Fairfax'
      WHEN 'fator' THEN 'Fator'
      WHEN 'gndi' THEN 'GNDI'
      WHEN 'goldencross' THEN 'Golden Cross'
      WHEN 'hapvidagndi' THEN 'Hapvida (GNDI)'
      WHEN 'hdi' THEN 'HDI'
      WHEN 'icatu' THEN 'Icatu'
      WHEN 'infinite' THEN 'Infinite'
      WHEN 'inovah' THEN 'Inovah'
      WHEN 'ita' THEN 'Itaú'
      WHEN 'jns' THEN 'JNS'
      WHEN 'junto' THEN 'Junto'
      WHEN 'kovr' THEN 'KOVR'
      WHEN 'liberty' THEN 'Liberty'
      WHEN 'mapfre' THEN 'Mapfre'
      WHEN 'mbm' THEN 'MBM'
      WHEN 'medsnior' THEN 'Med Sênior'
      WHEN 'metlife' THEN 'MetLife'
      WHEN 'mitsui' THEN 'Mitsui'
      WHEN 'mongeralaegon' THEN 'Mongeral Aegon'
      WHEN 'now' THEN 'Now'
      WHEN 'odontoprev' THEN 'OdontoPrev'
      WHEN 'omint' THEN 'Omint'
      WHEN 'pottencial' THEN 'Pottencial'
      WHEN 'preventsenior' THEN 'Prevent Senior'
      WHEN 'prudential' THEN 'Prudential'
      WHEN 'socristvo' THEN 'São Cristóvão'
      WHEN 'sombrero' THEN 'Sombrero'
      WHEN 'sompo' THEN 'Sompo'
      WHEN 'suhai' THEN 'Suhai'
      WHEN 'swissbradesco' THEN 'Swiss (Bradesco)'
      WHEN 'thinkseg' THEN 'ThinkSeg'
      WHEN 'unimed' THEN 'Unimed'
      WHEN 'unimedrs' THEN 'Unimed RS'
      WHEN 'vitaegroup' THEN 'Vitae Group'
      WHEN 'zurich' THEN 'Zurich'
      ELSE initcap(btrim(p_seguradora))
    END
  END;
$$;