INSERT INTO public.permissoes_catalogo (chave, rotulo, area, descricao, exige_concessao, ordem) VALUES
('menu_inicio','Hub (Início)','Menu Principal','Tela inicial com blocos e atualizações',false,10),
('menu_reserva_posicoes','Reserva de Posições','Menu Principal','Mapa do escritório, reserva por horário e minhas reservas',false,20),
('menu_dashboards','Dashboards','Dashboards','Controle mestre do grupo Dashboards',false,30),
('menu_dashboard_receita','Receita','Dashboards','Dashboard de Receita (Competência x Caixa)',false,40),
('menu_dashboard_receita_caixa','Receita Caixa','Dashboards','Detalhamento por caixa',false,50),
('menu_dashboard_receita_executivo','Resumo Executivo','Dashboards','Visão executiva consolidada',false,60),
('menu_dashboard_report_fechamento','Report Fechamento','Dashboards','Report de fechamento mensal',false,70),
('menu_area_financeiro','Financeiro','Áreas','Controle mestre do grupo Financeiro',false,80),
('menu_financeiro_fluxo_diario','Fluxo Diário','Áreas','Previsão de recebimento e repasse',false,90),
('menu_area_comercial','Comercial','Áreas','Controle mestre do grupo Comercial',false,100),
('menu_comercial_canal_parceiros','Canal Parceiros','Áreas','Cadastro único de parceiro, contratos e vigências',false,110),
('menu_area_juridico','Jurídico','Áreas',null,false,120),
('menu_juridico_contratos','Contrato de Parceria','Áreas','Contratos de parceria dos canais',false,125),
('juridico_renovar_contrato','Renovar contrato','Áreas','Ação com alçada — exige concessão nominal',true,126),
('juridico_suspender_contrato','Suspender contrato','Áreas','Ação com alçada — exige concessão nominal',true,127),
('juridico_bloquear_repasse','Bloquear repasse','Áreas','Ação com alçada — exige concessão nominal',true,128),
('menu_area_operacional','Operacional','Áreas',null,false,130),
('menu_area_middle','Middle','Áreas',null,false,140),
('menu_area_facilities','Facilities','Áreas',null,false,150),
('menu_rh_controle_posicoes','Controle de Posições','RH','Reservas, comparecimentos e ranking do escritório',false,160),
('menu_entrada_demandas','Entrada de Demandas','Entrada de Demandas','Porta única de registro de demandas de todos os ramos',false,170),
('entrada_cadastrar_canal','Cadastrar canal novo','Entrada de Demandas','Incluir canal/parceiro novo na lista',false,180),
('entrada_definir_responsavel','Definir responsável pelo cliente','Entrada de Demandas','Atribuir ou trocar o responsável de um cliente',false,190),
('menu_ramo_garantia','Garantia','Ramos','Controle mestre do grupo Garantia',false,200),
('menu_garantia_operacional','Operacional','Ramos','Análise de limite / auditoria T&C',false,210),
('menu_garantia_analise_processos','Análise de Processos','Ramos','Fila de originação por processo',false,220),
('menu_garantia_formulario_admin','Formulário Admin','Ramos','Demandas recebidas pelo formulário público de Garantia Judicial',false,230),
('menu_garantia_negociacao','Negociação','Ramos','Pipeline de negociação do ramo Garantia',false,240),
('menu_garantia_crm','CRM','Ramos','CRM pós-aceite e apólices de Garantia',false,250),
('menu_garantia_painel','Painel da Gerência','Ramos','Gargalos, tempos e conversão',false,260),
('menu_garantia_comercial','Comercial (fila de pendências)','Ramos','Demandas de Garantia aguardando retorno do comercial',false,270),
('menu_ramo_beneficios','Benefícios','Ramos',null,false,280),
('menu_ramo_demais','Demais Ramos','Ramos',null,false,290),
('ab_garantia','Originação (Garantia)','Análise Background','Fila por ramo, carteira, prêmio, comissão e prioridade',false,300),
('ab_juridico','Consulta processual (Jurídico)','Análise Background','Acervo de processos e andamentos',false,310),
('ab_compliance','Background de cliente e fornecedor','Análise Background','Dossiê de PJ por CNPJ',false,320),
('ab_rh','Background de colaborador e candidato','Análise Background','Dossiê de CPF, com trava de base legal (LGPD)',false,330),
('ab_solicitar','Solicitar pesquisa de processos','Análise Background','Ação: abre pedido que pode gerar consulta paga',true,340),
('ab_cota_gerir','Gerir cota e custos','Análise Background','Ação: define o teto mensal por área',true,350),
('menu_admin_usuarios','Usuários','Administração','Gestão de usuários do Hub',false,360),
('menu_admin_perfis','Perfis de Acesso','Administração','Gerenciar perfis',false,370),
('menu_admin_comunicados','Comunicados','Administração','Popups e comunicados internos',false,380),
('menu_admin_importar','Importar Bases','Administração','Página de upload de bases',false,390),
('menu_importar_gerencial','Base Gerencial (Lavoro)','Administração','Upload da base gerencial',false,400),
('menu_importar_caixa','Caixa Bradesco','Administração','Upload da base de caixa',false,410),
('menu_admin_emails','E-mails','Administração','Destinatários e templates',false,420),
('menu_admin_emails_schedules','Agendamentos','Administração','Configurar disparos recorrentes',false,430),
('menu_admin_emails_log','Log de E-mails','Administração','Histórico de envios',false,440),
('menu_admin_uso','Relatório de Uso','Administração','Uso diário por usuário e auditoria administrativa',false,450),
('menu_admin_reservas','Reserva de Posições (admin)','Administração','Posições, reservas de todos, parâmetros e modelos de e-mail',false,460),
('menu_admin_configuracoes','Configurações','Administração','Configurações gerais do Hub',false,470)
ON CONFLICT (chave) DO NOTHING;