// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://primmycdkkiziyhqkkkv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InByaW1teWNka2tpeml5aHFra2t2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODM1MzQ0MDAsImV4cCI6MjA5OTExMDQwMH0._htjVkyhWr21gLcztb873HWu9O2BL0HELTLu1jGrPiQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});